name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Generate HTML Artifact file that includes all about the failure
      - name: Run Lint
        run: echo Run Lint
#        run: ./gradlew lintDebug

#      - name: Upload html test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: lint-report
#          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: echo Run test
#        run: ./gradlew test

#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: unit-test-report
#          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run espresso tests
        run: echo Run espresso test
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: instrumentation-test-report
#          path: app/build/reports/androidTests/connected/debug/

  static-code-analysis:
    needs: [instrumentation-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Sonar Cloud Scan
        run: ./gradlew app:sonar -Dsonar.login=${{secrets.SONAR_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

